### ISSUE TITLE
[K000][Question] Hỏi về khởi chạy Rails server

### ISSUE THREAD

**Issue by nhanmvptit** [jackiedo91/it-background-ruby-on-rails-fast-training#6]
### Dùng câu lệnh **rails server** để mở port 3000 nhưng không được.
Mình làm theo trang này:[https://guides.rubyonrails.org/getting_started.html](url)
nhưng đến bước **4.1 Starting up the Web Server** thì không thể start up được.
Lỗi được hiện ra như sau:
`=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	76: from bin/rails:3:in `<main>'
	75: from bin/rails:3:in `load'
	74: from /Users/nhanmaivan/Desktop/Projects/blog/bin/spring:15:in `<top (required)>'
	73: from /Users/nhanmaivan/Desktop/Projects/blog/bin/spring:15:in `require'
	72: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	71: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	70: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	69: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	68: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	67: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	66: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	65: from /Users/nhanmaivan/Desktop/Projects/blog/bin/rails:9:in `<top (required)>'
	64: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	63: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	62: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	61: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	60: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	59: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	58: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	57: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	56: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	55: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	54: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	53: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	52: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	51: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	50: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	49: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	48: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	47: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:37:in `start'
	46: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	45: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
	44: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
	43: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	42: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
	41: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
	40: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
	39: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
	38: from config.ru:3:in `block in <main>'
	37: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
	36: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	35: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	34: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	33: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	32: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	31: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	30: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	29: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	28: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	27: from /Users/nhanmaivan/Desktop/Projects/blog/config/environment.rb:5:in `<main>'
	26: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
	25: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	24: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	23: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	22: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	21: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
	20: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
	19: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	18: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	17: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	16: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	15: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	14: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
	13: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	12: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
	11: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker.rb:35:in `bootstrap'
	10: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/commands.rb:25:in `bootstrap'
	 9: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:18:in `refresh'
	 8: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:83:in `load'
	 7: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:51:in `public_manifest_path'
	 6: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:47:in `public_output_path'
	 5: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:43:in `public_path'
	 4: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:84:in `fetch'
	 3: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:88:in `data'
	 2: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92:in `load'
	 1: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92:in `read'
/Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92:in `read': No such file or directory @ rb_sysopen - /Users/nhanmaivan/Desktop/Projects/blog/config/webpacker.yml (Errno::ENOENT)
	75: from bin/rails:3:in `<main>'
	74: from bin/rails:3:in `load'
	73: from /Users/nhanmaivan/Desktop/Projects/blog/bin/spring:15:in `<top (required)>'
	72: from /Users/nhanmaivan/Desktop/Projects/blog/bin/spring:15:in `require'
	71: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	70: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	69: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	68: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	67: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	66: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	65: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	64: from /Users/nhanmaivan/Desktop/Projects/blog/bin/rails:9:in `<top (required)>'
	63: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	62: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	61: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	60: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	59: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	58: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	57: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	56: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	55: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	54: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	53: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	52: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	51: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	50: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	49: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	48: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	47: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	46: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:37:in `start'
	45: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	44: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
	43: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
	42: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	41: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
	40: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
	39: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
	38: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
	37: from config.ru:3:in `block in <main>'
	36: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
	35: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	34: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	33: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	32: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	31: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	30: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	29: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	28: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	27: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	26: from /Users/nhanmaivan/Desktop/Projects/blog/config/environment.rb:5:in `<main>'
	25: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
	24: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	23: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	22: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	21: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	20: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
	19: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
	18: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	17: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	16: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	15: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	14: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	13: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
	12: from /Users/nhanmaivan/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	11: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
	10: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker.rb:35:in `bootstrap'
	 9: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/commands.rb:25:in `bootstrap'
	 8: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:18:in `refresh'
	 7: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:83:in `load'
	 6: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:51:in `public_manifest_path'
	 5: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:47:in `public_output_path'
	 4: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:43:in `public_path'
	 3: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:84:in `fetch'
	 2: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:88:in `data'
	 1: from /Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:91:in `load'
/Users/nhanmaivan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found /Users/nhanmaivan/Desktop/Projects/blog/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/nhanmaivan/Desktop/Projects/blog/config/webpacker.yml (RuntimeError)`
Mình cố gắng đọc và tìm hiểu đủ chổ mà vẫn chưa được nữa, mong Huy Troubleshoot giúp mình với, cảm ơn Huy nhiều nhé!

**Comment by jackiedo91** [comment]
đã fixed
